package com.example.order.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.UUID;

@Data
@DynamoDBTable(tableName = "Orders")
public class Order {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String orderId;

    @DynamoDBAttribute
    private String customerName;

    @DynamoDBAttribute
    private double orderAmount;

    @DynamoDBAttribute
    private String orderDate;

    @DynamoDBAttribute
    private String invoiceFileUrl;

    // Generate order ID and date before saving
    public void generateIdAndDate() {
        if(orderId == null) {
            this.orderId = UUID.randomUUID().toString();
        }
        if(orderDate == null) {
            this.orderDate = LocalDateTime.now().format(DateTimeFormatter.ISO_DATE_TIME);
        }
    }
}